# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('action_name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CsvJobItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_values', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=40, null=True)),
                ('csv_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_jobs', to='csv_uploader.CsvJob')),
            ],
        ),
    ]
