# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvjobitem',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
